# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:



jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./${{ github.event.pull_request.title }}
    steps:
      - uses: actions/checkout@v3

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Perm
        run: chmod +x gradlew

      - name: Execute Gradle build
        run: ./gradlew build

      - name: Generate Jacoco report
        run: ./gradlew jacocoTestReport


      - name: Generate javadoc
        run: ./gradlew javadoc

      - name: snd
        run: tree


      - name: thr
        run: tree
      - name: Publish jacocoTest
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
          clean: clean
          folder: Task_1_1_1/build/reports/jacoco/test/html/
          target-folder: ${{ github.event.pull_request.title }}


  checkstyle:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Run check style
        uses: nikitasavinov/checkstyle-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          checkstyle_config: '.github/google_checks.xml'
          reporter: 'github-pr-check'
